language: java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittests -f /Users/gabe.clark/Practice/codecovdemo/src/test
  - bash <(curl -s https://codecov.io/bash) -F integrationTests -f /Users/gabe.clark/Practice/codecovdemo/src/test-integration

