language: java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  gradle clean test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash) -F unittests -f $home/Practice/codecovdemo/build/reports/jacoco/test/jacocoTestReport.xml
  gradle testIntegration jacocoTestReport
  - bash <(curl -s https://codecov.io/bash) -F integrationTests -f $home/Practice/codecovdemo/build/reports/jacoco/test/jacocoTestReport.xml

