# The codecov yaml contains all configuration settings.
# Project refers to *production*
coverage:
  status:
    project:
      default:
        # basic
        target: 80% # coverage we are trying to achieve
        threshold: 2% # coverage difference allowed to succeed
        base: auto

# Patch refers to changes being made within *this* PR
coverage:
  status:
    patch:
      default:
        # basic
        target: 80% # says this PR must be x% covered
        threshold: null
        base: auto
