coverage:
  status:
    project:
      default:
        # basic
        target: 80% # coverage we are trying to achieve
        threshold: 2% # coverage difference allowed to succeed
        base: auto

coverage:
  status:
    patch:
      default:
        # basic
        target: 80% # says this PR must be x% covered
        threshold: 2%
        base: auto

